# Generated by Django 4.1.3 on 2023-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
